version: '3'
services:
  web:
    image: php:7.4-apache
    volumes:
      - ./php:/var/www/html/php
      - ./img:/var/www/html/img
      - ./js:/var/www/html/js
      - ./css:/var/www/html/css
      - ./index.html:/var/www/html/index.html
    ports:
      - "8080:80"
  php:
    image: php:7.4
    volumes:
      - ./php:/var/www/html/php
      - ./img:/var/www/html/img
      - ./js:/var/www/html/js
      - ./css:/var/www/html/css
      - ./index.html:/var/www/html/index.html
    networks:
      - mynetwork
networks:
  mynetwork: