version: '3'
services:
  web:
    image: php:7.4-apache
    volumes:
      - ./img:/var/www/html/img
      - ./js:/var/www/html/js
      - ./css:/var/www/html/css
      - ./php:/var/www/html/php
    ports:
      - "8080:80"
    networks:
      - mynetwork
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=registration_form
      - MYSQL_USER=registration_form
      - MYSQL_PASSWORD=password 
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 #allowing of no password (True)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
networks:
  mynetwork: