version: '3'
services:
  web:
    image: financial-dashboard
    build: .
    volumes:
      - ./php:/var/www/html/php
    ports:
      - "8080:80"
  db: 
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=registration_form
      - MYSQL_USER=registration_form
      - MYSQL_PASSWORD=password
    volumes:
      - "./php:/docker-entrypoint-initdb.d" #sync persistent sql files with container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306